[package]
authors.workspace = true
edition = "2021"
license-file.workspace = true
name = "github_client"
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
